apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: car-controller
  description: Car Controller
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: 
