apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: driver-controller
  description: Driver Controller
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: springbootapp
  dependsOn: ['component:driver-mapper','component:car-already-in-use-exception','component:constraints-violation-exception']
