site_name: 'Controllers'
repo_url: https://github.com/derek-sweetman/springbootapp
repo_name: 'springbootapp'

nav:
  - CarController: carcontroller.md
  - DriverController: drivercontroller.md

plugins:
  - techdocs-core
