apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springbootapp
  annotations:
    github.com/project-slug: derek-sweetman/springbootapp
spec:
  type: other
  lifecycle: unknown
  owner: guests
