apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: car-already-in-use-exception
  description: Car Already In Use Exception
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: RabbitMQ  
