apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: constraints-violation-exception
  description: Constraints Violation Exception
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: springbootapp
