site_name: 'Exceptions'

repo_name: 'springbootapp'

nav:
  - Home: index.md
  - Constraints Violation Exception: ConstraintsViolationException.md
  - Car Already in Use Exception: caralreadyinuseexception.md


plugins:
  - techdocs-core
