apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: car-service
  description: Car Service
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: springbootapp
  dependsOn: ['component:car-already-in-use-exception', 'component:constraints-violation-exception']
