apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: car-mapper
  description: Car Mapper
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: springbootapp
  depends on: ['component:car-mapper']
