apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: logger-activity
  description: Logger Activity
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: RabbitMQ
  dependsOn: ['component:DriverMapper']
  
