apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: driver-mapper
  description: Driver Mapper
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: springbootapp
  dependsOn: ['component:driver-dto','component:driver-do']
