site_name: 'Mappers'
repo_url: https://github.com/derek-sweetman/springbootapp
repo_name: 'springbootapp'

nav:
  - CarMapper: carmapper.md
  - DriverMapper: drivermapper.md

plugins:
  - techdocs-core
