apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: driver-do
  description: Driver DO
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: springbootapp
