site_name: 'Domain Objects'
repo_url: https://github.com/derek-sweetman/springbootapp
repo_name: 'springbootapp'

nav:
  - CarDO: carmapper.md
  - DriverDO: drivermapper.md

plugins:
  - techdocs-core
