apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: default-driver-service
  description: Default Driver Service
  annotations:
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: springbootapp
  dependsOn: ['component:constraints-violation-exception']
