site_name: 'Driver'

repo_name: 'springbootapp'

nav:
  - Home: index.md
  - Driver Service: driverservice.md
  - Default Driver Service: defaultdriverservice.md
  - Default Driver Service Javadocs: defaultDriverServiceJavadocs.md


plugins:
  - techdocs-core
